SCGHRPortal/SCGHRPortal/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SCGHRPortal.BLL;
using SCGHRPortal.Models;

namespace SCGHRPortal.Controllers
{
    public class ApplicantController : Controller
    {
        // GET: Applicant
        public ActionResult ListApplicants()
        {
            var manager = new ApplicantManager();
            var applicant = manager.ListAllApplicants();

            return View(applicant.ToList());
        }

        [HttpGet]
        public ActionResult AddApplicant()
        {
           
            return View(new Applicant());
        }

        [HttpPost]
        public ActionResult AddApplicant(Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                //var manager = new ApplicantManager();
                //manager.AddApplicant(applicant);
                return View("CompletedApplication", applicant);
            }
            else
            {
                return View(applicant);
            }
            

           
        }
    }
}

SCGHRPortal/SCGHRPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCGHRPortal.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        
       


    }
}

SCGHRPortal/SCGHRPortal/Controllers/PolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SCGHRPortal.BLL;
using SCGHRPortal.Models;

namespace SCGHRPortal.Controllers
{
    public class PolicyController : Controller
    {
        //// GET: Policy
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public  ActionResult ListPolicies ()
        {
            var manager = new  PolicyManager();
            var policy = manager.GetAllPolicies();

           return View(policy.ToList());
        }

        [HttpGet]
        public ActionResult AddPolicy()
        {
            return View(new Policy());
        }

        [HttpPost]
        public ActionResult AddPolicy(Policy policy)
        {
            var manager = new PolicyManager();
            manager.AddPolicy(policy);

            return  RedirectToAction("ListPolicies");
        }

        [HttpGet]
        public ActionResult ListCategories()
        {
            var manager = new CategoryManager();
            var categories = manager.GetAllCategories();

            return View(categories.ToList());
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View(new Category());
        }

        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            var manager = new CategoryManager();
            manager.AddCategory(category);

            return RedirectToAction("ListCategories");
        }

        [HttpGet]
        public ActionResult EditCategory(int categoryId)
        {
            var manager = new CategoryManager();
            var category = manager.GetOneSpecificCategory(categoryId);

            return View(category);
        }

        [HttpPost]
        public ActionResult EditCategory(Category category)
        {
            var manager = new CategoryManager();
            manager.EditCategory(category);

            return RedirectToAction("AddCategory");
        }

       



    }
}

SCGHRPortal/SCGHRPortal/Views/Policy/AddCategory.cshtml
@model SCGHRPortal.Models.Category

@{
    ViewBag.Title = "AddCategory";
}

<h2>AddCategory</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <label>Category Name</label>
                <input type="text" name="txtddl" id="txtddl"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Add" class="btn btn-primary" onclick="AddCategoryToDropdown();"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <select id="ddl">   
                </select>
            </div>
        </div>
      
    </div>

}

<div>
    @Html.ActionLink("Back to List", "ListCategories")
</div>



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/app/AddCategoryToDropdown.js"></script>

SCGHRPortal/SCGHRPortal/Views/Policy/AddPolicy.cshtml
@model SCGHRPortal.Models.Policy

@{
    ViewBag.Title = "AddPolicy";
}


<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("PolicyNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <div class="col-xs-12">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Policy</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.PolicyName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PolicyName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PolicyName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                            <div>
                                @Html.ActionLink("Back to List", "ListPolicies")
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SCGHRPortal/SCGHRPortal/Views/Policy/EditCategory.cshtml
@model SCGHRPortal.Models.Category

@{
    ViewBag.Title = "EditCategory";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryId)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListCategories")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SCGHRPortal/SCGHRPortal/Views/Policy/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("PolicyNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <p>
            This is the student area of the web site.  We can list, add, edit, and delete student information here.
        </p>
    </div>
</div>

SCGHRPortal/SCGHRPortal/Views/Policy/ListCategories.cshtml
@model IEnumerable<SCGHRPortal.Models.Category>

@{
    ViewBag.Title = "ListCategories";
}

<h2>ListCategories</h2>

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("PolicyNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <div class="col-xs-12">
                <h4>View Policies</h4>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.CategoryName)
                        </th>
                        <th>
                            @Html.Label("Options")
                        </th>

                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoryName)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "EditCategory", new { id = item.CategoryId }) |
                                @Html.ActionLink("Delete", "DeleteCategory", new { id = item.CategoryId })
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</div>

SCGHRPortal/SCGHRPortal/Views/Policy/ListPolicies.cshtml
@model IEnumerable<SCGHRPortal.Models.Policy>

@{
    ViewBag.Title = "ListPolicies";
}


<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("PolicyNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <div class="col-xs-12">
                <h4>View Policies</h4>
                @using (Html.BeginForm())
                {
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.PolicyName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PolicyName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>

                            </tr>
                        }

                    </table>


                }
            </div>
        </div>
    </div>
</div>

SCGHRPortal/SCGHRPortal/Views/Shared/ApplicantNav.cshtml
@{
    ViewBag.Title = "ApplicantNav";
}

<h4>Applicant Menu</h4>
<ul class="nav nav-pills nav-stacked">
    <li>@Html.ActionLink("Application Form", "AddApplicant", "Applicant")</li>
    <li>@Html.ActionLink("List Applicants", "ListApplicants", "Applicant")</li>
    
</ul>

SCGHRPortal/SCGHRPortal/Views/Shared/PolicyNav.cshtml
@{
    ViewBag.Title = "PolicyNav";
}
<h4>Policies Menu</h4>
<ul class="nav nav-pills nav-stacked">
    <li>@Html.ActionLink("View Policies", "ListPolicies", "Policy")</li>
    <li>@Html.ActionLink("Manage Policies", "AddPolicy", "Policy")</li>
    <li>@Html.ActionLink("Manage Categories", "AddCategory", "Policy")</li>
</ul>

SCGHRPortal/SCGHRPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
   
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("SG HR Portal", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Application Form", "AddApplicant", "Applicant")</li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("View Policies", "ListPolicies", "Policy")</li>
                        <li>@Html.ActionLink("Manage Policies", "AddPolicy", "Policy")</li>
                        <li>@Html.ActionLink("Manage Categories", "AddCategory", "Policy")</li>
                    </ul>
           </ul>
        </div>
    </div>
</div>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Created by Emre Biber</p>
    </footer>
</div>

@*@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")*@
@RenderSection("scripts", required: false)
</body>
</html>