ModelValidation2/ModelValidation2/Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.DynamicData;
using ModelValidation2.Models.Attributes;

namespace ModelValidation2.Models
{
    //[NoGarfieldOnMondays(ErrorMessage =  "No Garfield on Mondays! EVER!")]
    public class Appointment : IValidatableObject
    {
        /// <summary>
        /// in required attribute we could put error message too
        /// [Required(ErrorMessage = "You must enter name")]
        /// </summary>
        //[Required]
        [DisplayName("Your Name")]
        public string ClientName { get; set; }

        [DataType(DataType.Date)]
       // [Required(ErrorMessage = "Please enter a date")]
       [FutureDate(ErrorMessage= "Please enter a date in the future")]
        public DateTime Date { get; set; }

        //[Range(typeof(bool), "true", "true", ErrorMessage = "You must accept the terms")]
       // [MustBeTrue(ErrorMessage = "You must accept my custom terms")]
        public bool TermsAccepted { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (string.IsNullOrEmpty(ClientName))
            {
                errors.Add(new ValidationResult("Please enter your name", new [] {"ClientName"}));
            }

            if (DateTime.Now > Date)
            {
                errors.Add(new ValidationResult("Please select a future date", new [] {"Date"}));
            }

            if (errors.Count == 0 && ClientName == "Garfield" && Date.DayOfWeek == DayOfWeek.Monday)
            {
                errors.Add(new ValidationResult("Garfield cannot book appoinment on Mondays"));
            }

            if (!TermsAccepted)
            {
                errors.Add(new ValidationResult("You must accept the terms", new []{"TermsAccepted"}));
            }

            return errors;
        }
    }
}

ModelValidation2/ModelValidation2/Models/Attributes/FutureDateAttribute.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ModelValidation2.Models
{
    public class FutureDateAttribute : RequiredAttribute
    {
        public override bool IsValid(object value)
        {
            return base.IsValid(value) && ((DateTime)value) > DateTime.Now;
        }
    }
}

ModelValidation2/ModelValidation2/Models/Attributes/MustBeTrueAttribute.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ModelValidation2.Models.Attributes
{
    public class MustBeTrueAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            bool valid = false;
            valid = (value is bool && (bool) value == true);
            return valid;
        }
    }
}

ModelValidation2/ModelValidation2/Models/Attributes/NoGarfieldOnMondaysAttribute.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ModelValidation2.Models.Attributes
{
    public class NoGarfieldOnMondaysAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            Appointment appt = value as Appointment;
            if (appt == null || string.IsNullOrEmpty(appt.ClientName))
            {
                return true;
            }
            else
            {
                return !(appt.ClientName == "Garfield" && appt.Date.DayOfWeek == DayOfWeek.Monday);
            }
            
        }
    }
}

ModelValidation2/ModelValidation2/Controllers/AppoinmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelValidation2.Models;

namespace ModelValidation2.Controllers
{
    public class AppoinmentController : Controller
    {
        // GET: Appoinment
        public ActionResult MakeBooking()
        {
            return View(new Appointment() {Date = DateTime.Now});
        }

        [HttpPost]
        public ActionResult MakeBooking(Appointment appt)
        {
            //Explicit validation
            //if (string.IsNullOrEmpty(appt.ClientName))
            //{
            //    ModelState.AddModelError("ClientName", "Please enter your name");
            //}
            //if (ModelState.IsValidField("Date") && DateTime.Now > appt.Date)
            //{
            //    ModelState.AddModelError("Date", "Please enter a date in the future");
            //}
            //if (!appt.TermsAccepted)
            //{
            //    ModelState.AddModelError("TermsAccepted", "You must accept the terms and conditions");
            //}
            //if (ModelState.IsValidField("ClientName") && ModelState.IsValidField("Date"))
            //{
            //    if (appt.ClientName == "Garfield" && appt.Date.DayOfWeek == DayOfWeek.Monday)
            //    {
            //        ModelState.AddModelError("", "Garfield can't book appoinments on monyda");
            //    }
            //}



            if (ModelState.IsValid)
            {
                //This is where I would persist my data
                return View("Completed", appt);
            }

            return View(appt);
        }
    }
}

ModelValidation2/ModelValidation2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ModelValidation2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ModelValidation2/ModelValidation2/Views/Appoinment/Completed.cshtml
@model ModelValidation2.Models.Appointment

@{
    ViewBag.Title = "Completed";
}

<h2>Completed</h2>

<h4>Your appoinment is confirmed</h4>
<p>Your name is: <b>@Html.DisplayFor(m => m.ClientName)</b></p>
<p>The date of your appoinment is: <b>@Html.DisplayFor(m => m.Date)</b></p>

ModelValidation2/ModelValidation2/Views/Appoinment/MakeBooking.cshtml
@model ModelValidation2.Models.Appointment

@{
    ViewBag.Title = "MakeBooking";
}

<h2>MakeBooking</h2>

@Html.ValidationSummary(true)

@using (Html.BeginForm())
{
    <p>Your name: @Html.EditorFor(m => m.ClientName)<br/>@Html.ValidationMessageFor(m=>m.ClientName)</p>
    <p>Appoinment date: @Html.EditorFor(m => m.Date)<br />@Html.ValidationMessageFor(m => m.Date)</p>
    <p>@Html.EditorFor(m => m.TermsAccepted)I accept the terms & conditions<br />@Html.ValidationMessageFor(m => m.TermsAccepted) </p>
    <input type ="submit" value="Make Booking"/>

}

ModelValidation2/ModelValidation2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Book Appoinment", "MakeBooking", "Appoinment")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>